/* prjParams.h - dynamically generated configuration header */


/*
GENERATED: Wed May 28 16:09:43 中国标准时间 2008
DO NOT EDIT - file is regenerated whenever the project changes
*/

#ifndef INCprjParamsh
#define INCprjParamsh


/*** INCLUDED COMPONENTS ***/

#define INCLUDE_ANSI_ASSERT
#define INCLUDE_ANSI_CTYPE
#define INCLUDE_ANSI_LOCALE
#define INCLUDE_ANSI_MATH
#define INCLUDE_ANSI_STDIO
#define INCLUDE_ANSI_STDIO_EXTRA
#define INCLUDE_ANSI_STDLIB
#define INCLUDE_ANSI_STRING
#define INCLUDE_ANSI_TIME
#define INCLUDE_ARP_API
#define INCLUDE_ATA
#define INCLUDE_ATA_SHOW
#define INCLUDE_AUX_CLK
#define INCLUDE_BOOT_LINE_INIT
#define INCLUDE_BSD_SOCKET
#define INCLUDE_BUF_MGR
#define INCLUDE_CACHE_ENABLE
#define INCLUDE_CACHE_SUPPORT
#define INCLUDE_CBIO
#define INCLUDE_CPLUS
#define INCLUDE_CPLUS_DEMANGLER
#define INCLUDE_CPLUS_IOSTREAMS
#define INCLUDE_CPLUS_IOSTREAMS_FULL
#define INCLUDE_CPLUS_LANG
#define INCLUDE_CPLUS_STL
#define INCLUDE_CPLUS_STRING
#define INCLUDE_CPLUS_STRING_IO
#define INCLUDE_CTORS_DTORS
#define INCLUDE_DEBUG
#define INCLUDE_DHCPC_LEASE_CLEAN
#define INCLUDE_DISK_CACHE
#define INCLUDE_DISK_PART
#define INCLUDE_DISK_UTIL
#define INCLUDE_DLL
#define INCLUDE_DOSFS
#define INCLUDE_DOSFS_CHKDSK
#define INCLUDE_DOSFS_DIR_FIXED
#define INCLUDE_DOSFS_DIR_VFAT
#define INCLUDE_DOSFS_FAT
#define INCLUDE_DOSFS_FMT
#define INCLUDE_DOSFS_MAIN
#define INCLUDE_END
#define INCLUDE_END_BOOT
#define INCLUDE_ENV_VARS
#define INCLUDE_EXC_HANDLING
#define INCLUDE_EXC_SHOW
#define INCLUDE_EXC_TASK
#define INCLUDE_FLOATING_POINT
#define INCLUDE_FORMATTED_IO
#define INCLUDE_FTP
#define INCLUDE_FTPD_SECURITY
#define INCLUDE_FTP_SERVER
#define INCLUDE_GNU_INTRINSICS
#define INCLUDE_HASH
#define INCLUDE_HOST_TBL
#define INCLUDE_HW_FP
#define INCLUDE_HW_FP_SHOW
#define INCLUDE_ICMP
#define INCLUDE_ICMP_SHOW
#define INCLUDE_IO_SYSTEM
#define INCLUDE_IP
#define INCLUDE_KERNEL
#define INCLUDE_LOADER
#define INCLUDE_LOGGING
#define INCLUDE_LOOPBACK
#define INCLUDE_LSTLIB
#define INCLUDE_MEMORY_CONFIG
#define INCLUDE_MEM_MGR_BASIC
#define INCLUDE_MEM_MGR_FULL
#define INCLUDE_MEM_SHOW
#define INCLUDE_MMU_BASIC
#define INCLUDE_MODULE_MANAGER
#define INCLUDE_MSG_Q
#define INCLUDE_MSG_Q_SHOW
#define INCLUDE_MUX
#define INCLUDE_NETDEV_CONFIG
#define INCLUDE_NETDEV_NAMEGET
#define INCLUDE_NETMASK_GET
#define INCLUDE_NETWORK
#define INCLUDE_NET_HOST_SETUP
#define INCLUDE_NET_INIT
#define INCLUDE_NET_LIB
#define INCLUDE_NET_REM_IO
#define INCLUDE_NET_SETUP
#define INCLUDE_NET_SHOW
#define INCLUDE_PING
#define INCLUDE_PIPES
#define INCLUDE_POSIX_CLOCKS
#define INCLUDE_RAMDRV
#define INCLUDE_RBUFF
#define INCLUDE_RNG_BUF
#define INCLUDE_RPC
#define INCLUDE_SECURITY
#define INCLUDE_SELECT
#define INCLUDE_SELECT_SUPPORT
#define INCLUDE_SEM_BINARY
#define INCLUDE_SEM_COUNTING
#define INCLUDE_SEM_MUTEX
#define INCLUDE_SEM_SHOW
#define INCLUDE_SHELL
#define INCLUDE_SHELL_BANNER
#define INCLUDE_SIGNALS
#define INCLUDE_SIO
#define INCLUDE_STANDALONE_SYM_TBL
#define INCLUDE_STAT_SYM_TBL
#define INCLUDE_STDIO
#define INCLUDE_SYM_TBL
#define INCLUDE_SYM_TBL_INIT
#define INCLUDE_SYM_TBL_SHOW
#define INCLUDE_SYSCLK_INIT
#define INCLUDE_SYSHW_INIT
#define INCLUDE_SYS_START
#define INCLUDE_SYS_TIMESTAMP
#define INCLUDE_TASK_HOOKS
#define INCLUDE_TASK_SHOW
#define INCLUDE_TASK_VARS
#define INCLUDE_TCP
#define INCLUDE_TCP_SHOW
#define INCLUDE_TELNET
#define INCLUDE_TIMESTAMP
#define INCLUDE_TIMEX
#define INCLUDE_TTY_DEV
#define INCLUDE_UDP
#define INCLUDE_UDP_SHOW
#define INCLUDE_USER_APPL
#define INCLUDE_VXEVENTS
#define INCLUDE_WATCHDOGS
#define INCLUDE_WDB
#define INCLUDE_WDB_BANNER
#define INCLUDE_WDB_BP
#define INCLUDE_WDB_COMM_END
#define INCLUDE_WDB_CTXT
#define INCLUDE_WDB_DIRECT_CALL
#define INCLUDE_WDB_EVENTPOINTS
#define INCLUDE_WDB_EVENTS
#define INCLUDE_WDB_EXC_NOTIFY
#define INCLUDE_WDB_EXIT_NOTIFY
#define INCLUDE_WDB_FUNC_CALL
#define INCLUDE_WDB_GOPHER
#define INCLUDE_WDB_HW_FP
#define INCLUDE_WDB_MEM
#define INCLUDE_WDB_REG
#define INCLUDE_WDB_START_NOTIFY
#define INCLUDE_WDB_SYS
#define INCLUDE_WDB_SYS_HW_FP
#define INCLUDE_WDB_TASK
#define INCLUDE_WDB_TASK_BP
#define INCLUDE_WDB_TASK_HW_FP
#define INCLUDE_WDB_TSFS
#define INCLUDE_WDB_USER_EVENT
#define INCLUDE_WDB_VIO
#define INCLUDE_WDB_VIO_LIB
#define INCLUDE_WINDVIEW
#define INCLUDE_WINDVIEW_CLASS
#define INCLUDE_WVUPLOAD_FILE
#define INCLUDE_WVUPLOAD_TSFSSOCK
#undef INCLUDE_PROTECT_TEXT
#undef INCLUDE_PROTECT_VEC_TABLE
#undef INCLUDE_PCI_PARAMS
#undef INCLUDE_VME_PARAMS
#undef INCLUDE_PCMCIA
#undef INCLUDE_SCSI
#undef INCLUDE_LPT
#undef INCLUDE_FD
#undef INCLUDE_DSP
#undef INCLUDE_IDE
#undef INCLUDE_PC_CONSOLE
#undef INCLUDE_TFFS
#undef INCLUDE_TFFS_SHOW
#undef INCLUDE_MTD_AMD
#undef INCLUDE_MTD_I28F008
#undef INCLUDE_MTD_I28F008BAJA
#undef INCLUDE_MTD_I28F016
#undef INCLUDE_MTD_WAMDMTD
#undef INCLUDE_MTD_CFIAMD
#undef INCLUDE_MTD_CFISCS
#undef INCLUDE_TL_FTL
#undef INCLUDE_TL_SSFDC
#undef INCLUDE_MMU_FULL
#undef INCLUDE_MMU_MPU
#undef INCLUDE_TYCODRV_5_2
#undef INCLUDE_SW_FP
#undef INCLUDE_DC
#undef INCLUDE_EGL
#undef INCLUDE_EI
#undef INCLUDE_FEI
#undef INCLUDE_EX
#undef INCLUDE_ENP
#undef INCLUDE_IE
#undef INCLUDE_ILAC
#undef INCLUDE_LN
#undef INCLUDE_LNSGI
#undef INCLUDE_NIC
#undef INCLUDE_NIC_EVB
#undef INCLUDE_MED
#undef INCLUDE_ELC
#undef INCLUDE_ULTRA
#undef INCLUDE_EEX
#undef INCLUDE_ELT
#undef INCLUDE_QU
#undef INCLUDE_ENE
#undef INCLUDE_ESMC
#undef INCLUDE_SN
#undef INCLUDE_OLI
#undef INCLUDE_USR_ENTRIES
#undef INCLUDE_IF_USR
#undef INCLUDE_LNEBSA
#undef INCLUDE_FN
#undef INCLUDE_BSD
#undef INCLUDE_ZBUF_SOCK
#undef INCLUDE_BSD_BOOT
#undef INCLUDE_PPP
#undef INCLUDE_PPP_BOOT
#undef INCLUDE_PPP_CRYPT
#undef INCLUDE_SLIP
#undef INCLUDE_SLIP_BOOT
#undef INCLUDE_RIP
#undef INCLUDE_ROUTE_SOCK
#undef INCLUDE_DNS_RESOLVER
#undef INCLUDE_DHCPC
#undef INCLUDE_DHCPR
#undef INCLUDE_DHCPS
#undef INCLUDE_SNTPC
#undef INCLUDE_SNTPS
#undef INCLUDE_RLOGIN
#undef INCLUDE_NFS
#undef INCLUDE_NFS_MOUNT_ALL
#undef INCLUDE_NFS_SERVER
#undef INCLUDE_TFTP_CLIENT
#undef INCLUDE_TFTP_SERVER
#undef INCLUDE_PROXY_CLIENT
#undef INCLUDE_PROXY_SERVER
#undef INCLUDE_TCP_DEBUG
#undef INCLUDE_IP_FILTER
#undef INCLUDE_IGMP
#undef BSD43_COMPATIBLE
#undef INCLUDE_MCAST_ROUTING
#undef INCLUDE_SM_NET_ADDRGET
#undef INCLUDE_SECOND_SMNET
#undef INCLUDE_SM_NET
#undef INCLUDE_SM_SEQ_ADDR
#undef INCLUDE_PROXY_DEFAULT_ADDR
#undef INCLUDE_MIB2_ALL
#undef INCLUDE_MIB2_AT
#undef INCLUDE_MIB2_ICMP
#undef INCLUDE_MIB2_IF
#undef INCLUDE_MIB2_IP
#undef INCLUDE_MIB2_SYSTEM
#undef INCLUDE_MIB2_TCP
#undef INCLUDE_MIB2_UDP
#undef INCLUDE_SNMPD
#undef INCLUDE_DHCPC_SHOW
#undef INCLUDE_IGMP_SHOW
#undef INCLUDE_SM_NET_SHOW
#undef INCLUDE_DHCPC_LEASE_TEST
#undef INCLUDE_DHCPC_LEASE_SAVE
#undef INCLUDE_DEFER_NET_INIT
#undef INCLUDE_DHCPC_LEASE_GET
#undef INCLUDE_SM_COMMON
#undef INCLUDE_TFFS_DOSFS
#undef INCLUDE_DIAB_INTRINSICS
#undef INCLUDE_NO_INTRINSICS
#undef INCLUDE_CPLUS_COMPLEX
#undef INCLUDE_CPLUS_COMPLEX_IO
#undef INCLUDE_POSIX_AIO
#undef INCLUDE_POSIX_AIO_SYSDRV
#undef INCLUDE_POSIX_FTRUNC
#undef INCLUDE_POSIX_MEM
#undef INCLUDE_POSIX_MQ
#undef INCLUDE_POSIX_PTHREADS
#undef INCLUDE_POSIX_SCHED
#undef INCLUDE_POSIX_SEM
#undef INCLUDE_POSIX_SIGNALS
#undef INCLUDE_POSIX_TIMERS
#undef INCLUDE_CLASS_SHOW
#undef INCLUDE_MMU_FULL_SHOW
#undef INCLUDE_POSIX_AIO_SHOW
#undef INCLUDE_POSIX_MQ_SHOW
#undef INCLUDE_POSIX_SEM_SHOW
#undef INCLUDE_STDIO_SHOW
#undef INCLUDE_TASK_HOOKS_SHOW
#undef INCLUDE_WATCHDOGS_SHOW
#undef INCLUDE_TRIGGER_SHOW
#undef INCLUDE_RBUFF_SHOW
#undef INCLUDE_PCI_CFGSHOW
#undef INCLUDE_DSP_SHOW
#undef INCLUDE_TRIGGERING
#undef INCLUDE_SPY
#undef INCLUDE_CODETEST
#undef INCLUDE_STARTUP_SCRIPT
#undef INCLUDE_SYM_TBL_SYNC
#undef INCLUDE_NET_SYM_TBL
#undef INCLUDE_UNLOADER
#undef INCLUDE_WDB_DSP
#undef INCLUDE_WDB_TASK_DSP
#undef INCLUDE_WDB_SYS_DSP
#undef INCLUDE_WDB_COMM_SERIAL
#undef INCLUDE_WDB_COMM_TYCODRV_5_2
#undef INCLUDE_WDB_COMM_NETWORK
#undef INCLUDE_WDB_COMM_NETROM
#undef INCLUDE_WDB_COMM_VTMD
#undef INCLUDE_WDB_COMM_CUSTOM
#undef INCLUDE_WDB_COMM_PIPE
#undef INCLUDE_CDROMFS
#undef INCLUDE_RT11FS
#undef INCLUDE_RAWFS
#undef INCLUDE_WVNET
#undef INCLUDE_WVUPLOAD_SOCK
#undef INCLUDE_USER_TIMESTAMP
#undef INCLUDE_SEQ_TIMESTAMP
#undef INCLUDE_WV_BUFF_USER
#undef INCLUDE_BPF
#undef INCLUDE_SCSI_DOSFS
#undef INCLUDE_TAR
#undef INCLUDE_RAM_DISK
#undef INCLUDE_EXC_EXTENDED_VECTORS
#undef INCLUDE_ALTIVEC
#undef INCLUDE_ALTIVEC_SHOW
#undef INCLUDE_WDB_ALTIVEC
#undef INCLUDE_WDB_TASK_ALTIVEC
#undef INCLUDE_COM_CORE
#undef INCLUDE_COM_SHOW
#undef INCLUDE_COM_NTP_TIME
#undef INCLUDE_COM


/*** PARAMETERS ***/

#undef  LOCAL_MEM_LOCAL_ADRS
#define LOCAL_MEM_LOCAL_ADRS 0x00000000
#undef  LOCAL_MEM_SIZE
#define LOCAL_MEM_SIZE 0x10000000
#undef  LOCAL_MEM_AUTOSIZE
#undef  USER_RESERVED_MEM
#define USER_RESERVED_MEM 0x05000000
#undef  NV_RAM_SIZE
#define NV_RAM_SIZE 0x7ffff
#undef  NV_BOOT_OFFSET
#define NV_BOOT_OFFSET 0
#undef  VEC_BASE_ADRS
#define VEC_BASE_ADRS ((char *) 0x0)
#undef  EXC_MSG_OFFSET
#define EXC_MSG_OFFSET 0x4300
#undef  EXC_MSG_ADRS
#define EXC_MSG_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+EXC_MSG_OFFSET))
#undef  BOOT_LINE_SIZE
#define BOOT_LINE_SIZE 255
#undef  BOOT_LINE_ADRS
#define BOOT_LINE_ADRS ((char *) (LOCAL_MEM_LOCAL_ADRS+BOOT_LINE_OFFSET))
#undef  BOOT_LINE_OFFSET
#define BOOT_LINE_OFFSET 0x4200
#undef  DEFAULT_BOOT_LINE
#define DEFAULT_BOOT_LINE "mv(0,0)yx:vxWorks.st h=192.168.2.134 e=192.168.2.144 u=vxworks pw=vxworks tn=vxworks"
#undef  RESERVED
#define RESERVED 0x4400
#undef  FREE_RAM_ADRS
#define FREE_RAM_ADRS (end)
#undef  ROM_WARM_ADRS
#define ROM_WARM_ADRS 0x00010008
#undef  STACK_SAVE
#define STACK_SAVE 0x1000
#undef  RAM_HIGH_ADRS
#define RAM_HIGH_ADRS 0x00400000
#undef  RAM_LOW_ADRS
#define RAM_LOW_ADRS 0x00010000
#undef  ROM_BASE_ADRS
#define ROM_BASE_ADRS 0x0
#undef  ROM_TEXT_ADRS
#define ROM_TEXT_ADRS 0x00010000
#undef  ROM_SIZE
#define ROM_SIZE 0x00080000
#undef  USER_I_CACHE_MODE
#define USER_I_CACHE_MODE CACHE_COPYBACK
#undef  USER_D_CACHE_MODE
#define USER_D_CACHE_MODE CACHE_COPYBACK
#undef  USER_I_CACHE_ENABLE
#define USER_I_CACHE_ENABLE
#undef  USER_D_CACHE_ENABLE
#define USER_D_CACHE_ENABLE
#undef  VM_PAGE_SIZE
#define VM_PAGE_SIZE 4096
#undef  USER_D_MMU_ENABLE
#define USER_D_MMU_ENABLE
#undef  USER_I_MMU_ENABLE
#define USER_I_MMU_ENABLE
#undef  SYS_CLK_RATE
#define SYS_CLK_RATE 100
#undef  SYS_CLK_RATE_MIN
#define SYS_CLK_RATE_MIN 3
#undef  SYS_CLK_RATE_MAX
#define SYS_CLK_RATE_MAX 5000
#undef  AUX_CLK_RATE_MIN
#define AUX_CLK_RATE_MIN 3
#undef  AUX_CLK_RATE_MAX
#define AUX_CLK_RATE_MAX 5000
#undef  NUM_TTY
#define NUM_TTY N_SIO_CHANNELS
#undef  CONSOLE_TTY
#define CONSOLE_TTY 0
#undef  CONSOLE_BAUD_RATE
#define CONSOLE_BAUD_RATE 9600
#undef  RT_BUFFERED_DISPLAY
#define RT_BUFFERED_DISPLAY FALSE
#undef  RT_DISPLAY_MEMORY
#define RT_DISPLAY_MEMORY 10000
#undef  END_POLL_STATS_ROUTINE_HOOK
#define END_POLL_STATS_ROUTINE_HOOK m2PollStatsIfPoll
#undef  IP_FLAGS_DFLT
#define IP_FLAGS_DFLT (IP_DO_CHECKSUM_SND | IP_DO_CHECKSUM_RCV)
#undef  IP_TTL_DFLT
#define IP_TTL_DFLT 64
#undef  IP_QLEN_DFLT
#define IP_QLEN_DFLT 50
#undef  IP_FRAG_TTL_DFLT
#define IP_FRAG_TTL_DFLT 60
#undef  ICMP_FLAGS_DFLT
#define ICMP_FLAGS_DFLT (ICMP_NO_MASK_REPLY)
#undef  UDP_FLAGS_DFLT
#define UDP_FLAGS_DFLT (UDP_DO_CKSUM_SND | UDP_DO_CKSUM_RCV)
#undef  UDP_SND_SIZE_DFLT
#define UDP_SND_SIZE_DFLT 9216
#undef  UDP_RCV_SIZE_DFLT
#define UDP_RCV_SIZE_DFLT 41600
#undef  TCP_FLAGS_DFLT
#define TCP_FLAGS_DFLT (TCP_DO_RFC1323)
#undef  TCP_SND_SIZE_DFLT
#define TCP_SND_SIZE_DFLT 8192
#undef  TCP_RCV_SIZE_DFLT
#define TCP_RCV_SIZE_DFLT 8192
#undef  TCP_CON_TIMEO_DFLT
#define TCP_CON_TIMEO_DFLT 150
#undef  TCP_REXMT_THLD_DFLT
#define TCP_REXMT_THLD_DFLT 3
#undef  TCP_MSS_DFLT
#define TCP_MSS_DFLT 512
#undef  TCP_RND_TRIP_DFLT
#define TCP_RND_TRIP_DFLT 3
#undef  TCP_IDLE_TIMEO_DFLT
#define TCP_IDLE_TIMEO_DFLT 14400
#undef  TCP_MAX_PROBE_DFLT
#define TCP_MAX_PROBE_DFLT 8
#undef  TCP_RAND_FUNC
#define TCP_RAND_FUNC (FUNCPTR)random
#undef  TCP_MSL_CFG
#define TCP_MSL_CFG 30
#undef  NUM_FILES
#define NUM_FILES 50
#undef  FTP_TRANSIENT_MAX_RETRY_COUNT
#define FTP_TRANSIENT_MAX_RETRY_COUNT 100
#undef  FTP_TRANSIENT_RETRY_INTERVAL
#define FTP_TRANSIENT_RETRY_INTERVAL 0
#undef  FTP_TRANSIENT_FATAL
#define FTP_TRANSIENT_FATAL ftpTransientFatal
#undef  FTP_DEBUG_OPTIONS
#define FTP_DEBUG_OPTIONS 0
#undef  TELNETD_MAX_CLIENTS
#define TELNETD_MAX_CLIENTS 1
#undef  TELNETD_TASKFLAG
#define TELNETD_TASKFLAG FALSE
#undef  TELNETD_PORT
#define TELNETD_PORT 23
#undef  TELNETD_PARSER_HOOK
#define TELNETD_PARSER_HOOK mcwillShellParserControl
#undef  LOGIN_USER_NAME
#define LOGIN_USER_NAME "bts"
#undef  LOGIN_PASSWORD
#define LOGIN_PASSWORD "Ryb9yReecQ"
#undef  NUM_NET_MBLKS
#define NUM_NET_MBLKS 400
#undef  NUM_CL_BLKS
#define NUM_CL_BLKS (NUM_64 + NUM_128 + NUM_256 + NUM_512 + NUM_1024 + NUM_2048)
#undef  NUM_64
#define NUM_64 100
#undef  NUM_128
#define NUM_128 100
#undef  NUM_256
#define NUM_256 40
#undef  NUM_512
#define NUM_512 40
#undef  NUM_1024
#define NUM_1024 25
#undef  NUM_2048
#define NUM_2048 25
#undef  NUM_SYS_MBLKS
#define NUM_SYS_MBLKS (2 * NUM_SYS_CL_BLKS)
#undef  NUM_SYS_CL_BLKS
#define NUM_SYS_CL_BLKS (NUM_SYS_64  + NUM_SYS_128 + NUM_SYS_256 + NUM_SYS_512)
#undef  NUM_SYS_64
#define NUM_SYS_64 64
#undef  NUM_SYS_128
#define NUM_SYS_128 64
#undef  NUM_SYS_256
#define NUM_SYS_256 64
#undef  NUM_SYS_512
#define NUM_SYS_512 64
#undef  IP_MAX_UNITS
#define IP_MAX_UNITS 3
#undef  ARP_MAX_ENTRIES
#define ARP_MAX_ENTRIES 0
#undef  CLEAR_BSS
#define CLEAR_BSS
#undef  SHELL_STACK_SIZE
#define SHELL_STACK_SIZE (20000)
#undef  SYM_TBL_HASH_SIZE_LOG2
#define SYM_TBL_HASH_SIZE_LOG2 8
#undef  STAT_TBL_HASH_SIZE_LOG2
#define STAT_TBL_HASH_SIZE_LOG2 6
#undef  WDB_STACK_SIZE
#define WDB_STACK_SIZE 0x2000
#undef  WDB_BP_MAX
#define WDB_BP_MAX 50
#undef  WDB_SPAWN_PRI
#define WDB_SPAWN_PRI 100
#undef  WDB_SPAWN_OPTS
#define WDB_SPAWN_OPTS VX_FP_TASK | VX_ALTIVEC_TASK
#undef  WDB_TASK_PRIORITY
#define WDB_TASK_PRIORITY 3
#undef  WDB_TASK_OPTIONS
#define WDB_TASK_OPTIONS VX_UNBREAKABLE | VX_FP_TASK | VX_ALTIVEC_TASK
#undef  WDB_RESTART_TIME
#define WDB_RESTART_TIME 10
#undef  WDB_MAX_RESTARTS
#define WDB_MAX_RESTARTS 5
#undef  WDB_MTU
#define WDB_MTU 1500
#undef  INCLUDE_CONSTANT_RDY_Q
#define INCLUDE_CONSTANT_RDY_Q
#undef  ROOT_STACK_SIZE
#define ROOT_STACK_SIZE (24000)
#undef  ISR_STACK_SIZE
#define ISR_STACK_SIZE (5000)
#undef  INT_LOCK_LEVEL
#define INT_LOCK_LEVEL 0x0
#undef  ENV_VAR_USE_HOOKS
#define ENV_VAR_USE_HOOKS TRUE
#undef  NUM_DOSFS_FILES
#define NUM_DOSFS_FILES 20
#undef  NUM_DRIVERS
#define NUM_DRIVERS 20
#undef  MAX_LOG_MSGS
#define MAX_LOG_MSGS 50
#undef  WV_DEFAULT_BUF_MIN
#define WV_DEFAULT_BUF_MIN 4
#undef  WV_DEFAULT_BUF_MAX
#define WV_DEFAULT_BUF_MAX 10
#undef  WV_DEFAULT_BUF_SIZE
#define WV_DEFAULT_BUF_SIZE 0x8000
#undef  WV_DEFAULT_BUF_THRESH
#define WV_DEFAULT_BUF_THRESH 0x4000
#undef  WV_DEFAULT_BUF_OPTIONS
#define WV_DEFAULT_BUF_OPTIONS 0x0
#undef  MUX_MAX_BINDS
#define MUX_MAX_BINDS 16
#undef  USR_MAX_LINK_HDR
#define USR_MAX_LINK_HDR 16
#undef  SOMAXCONN_CFG
#define SOMAXCONN_CFG 5
#undef  DOSFS_NAMES_ATA_PRIMARY_MASTER
#define DOSFS_NAMES_ATA_PRIMARY_MASTER "/ata0a"
#undef  DOSFS_NAMES_ATA_PRIMARY_SLAVE
#define DOSFS_NAMES_ATA_PRIMARY_SLAVE ""
#undef  DOSFS_NAMES_ATA_SECONDARY_MASTER
#define DOSFS_NAMES_ATA_SECONDARY_MASTER ""
#undef  DOSFS_NAMES_ATA_SECONDARY_SLAVE
#define DOSFS_NAMES_ATA_SECONDARY_SLAVE ""
#undef  ATA_CACHE_SIZE
#define ATA_CACHE_SIZE (128*1024)

#endif /* INCprjParamsh */
